// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: internal/grpc/proto/common.proto

package proto

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Sandbox types
type SandboxType int32

const (
	SandboxType_SANDBOX_TYPE_UNSPECIFIED SandboxType = 0
	SandboxType_SANDBOX_TYPE_LOCAL       SandboxType = 1
	SandboxType_SANDBOX_TYPE_REMOTE      SandboxType = 2
)

// Enum value maps for SandboxType.
var (
	SandboxType_name = map[int32]string{
		0: "SANDBOX_TYPE_UNSPECIFIED",
		1: "SANDBOX_TYPE_LOCAL",
		2: "SANDBOX_TYPE_REMOTE",
	}
	SandboxType_value = map[string]int32{
		"SANDBOX_TYPE_UNSPECIFIED": 0,
		"SANDBOX_TYPE_LOCAL":       1,
		"SANDBOX_TYPE_REMOTE":      2,
	}
)

func (x SandboxType) Enum() *SandboxType {
	p := new(SandboxType)
	*p = x
	return p
}

func (x SandboxType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SandboxType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_grpc_proto_common_proto_enumTypes[0].Descriptor()
}

func (SandboxType) Type() protoreflect.EnumType {
	return &file_internal_grpc_proto_common_proto_enumTypes[0]
}

func (x SandboxType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SandboxType.Descriptor instead.
func (SandboxType) EnumDescriptor() ([]byte, []int) {
	return file_internal_grpc_proto_common_proto_rawDescGZIP(), []int{0}
}

// GitHub integration types
type GitHubIssue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Number        int32                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo          string                 `protobuf:"bytes,4,opt,name=repo,proto3" json:"repo,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitHubIssue) Reset() {
	*x = GitHubIssue{}
	mi := &file_internal_grpc_proto_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitHubIssue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitHubIssue) ProtoMessage() {}

func (x *GitHubIssue) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitHubIssue.ProtoReflect.Descriptor instead.
func (*GitHubIssue) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_common_proto_rawDescGZIP(), []int{0}
}

func (x *GitHubIssue) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GitHubIssue) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *GitHubIssue) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GitHubIssue) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *GitHubIssue) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GitHubIssue) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type GitHubPR struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Number        int32                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo          string                 `protobuf:"bytes,4,opt,name=repo,proto3" json:"repo,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitHubPR) Reset() {
	*x = GitHubPR{}
	mi := &file_internal_grpc_proto_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitHubPR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitHubPR) ProtoMessage() {}

func (x *GitHubPR) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitHubPR.ProtoReflect.Descriptor instead.
func (*GitHubPR) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_common_proto_rawDescGZIP(), []int{1}
}

func (x *GitHubPR) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GitHubPR) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *GitHubPR) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GitHubPR) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *GitHubPR) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GitHubPR) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type TaskData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	GithubIssue   *GitHubIssue           `protobuf:"bytes,2,opt,name=github_issue,json=githubIssue,proto3" json:"github_issue,omitempty"`
	GithubPr      *GitHubPR              `protobuf:"bytes,3,opt,name=github_pr,json=githubPr,proto3" json:"github_pr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskData) Reset() {
	*x = TaskData{}
	mi := &file_internal_grpc_proto_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskData) ProtoMessage() {}

func (x *TaskData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskData.ProtoReflect.Descriptor instead.
func (*TaskData) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_common_proto_rawDescGZIP(), []int{2}
}

func (x *TaskData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TaskData) GetGithubIssue() *GitHubIssue {
	if x != nil {
		return x.GithubIssue
	}
	return nil
}

func (x *TaskData) GetGithubPr() *GitHubPR {
	if x != nil {
		return x.GithubPr
	}
	return nil
}

// Sandbox information
type SandboxInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          SandboxType            `protobuf:"varint,3,opt,name=type,proto3,enum=dispense.SandboxType" json:"type,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	ShellCommand  string                 `protobuf:"bytes,5,opt,name=shell_command,json=shellCommand,proto3" json:"shell_command,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Group         string                 `protobuf:"bytes,7,opt,name=group,proto3" json:"group,omitempty"`
	ProjectSource string                 `protobuf:"bytes,8,opt,name=project_source,json=projectSource,proto3" json:"project_source,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxInfo) Reset() {
	*x = SandboxInfo{}
	mi := &file_internal_grpc_proto_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxInfo) ProtoMessage() {}

func (x *SandboxInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxInfo.ProtoReflect.Descriptor instead.
func (*SandboxInfo) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_common_proto_rawDescGZIP(), []int{3}
}

func (x *SandboxInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SandboxInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SandboxInfo) GetType() SandboxType {
	if x != nil {
		return x.Type
	}
	return SandboxType_SANDBOX_TYPE_UNSPECIFIED
}

func (x *SandboxInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SandboxInfo) GetShellCommand() string {
	if x != nil {
		return x.ShellCommand
	}
	return ""
}

func (x *SandboxInfo) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SandboxInfo) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *SandboxInfo) GetProjectSource() string {
	if x != nil {
		return x.ProjectSource
	}
	return ""
}

func (x *SandboxInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Resource allocation for remote sandboxes
type ResourceAllocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      string                 `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Cpu           int32                  `protobuf:"varint,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        int32                  `protobuf:"varint,4,opt,name=memory,proto3" json:"memory,omitempty"`
	Disk          int32                  `protobuf:"varint,5,opt,name=disk,proto3" json:"disk,omitempty"`
	AutoStop      int32                  `protobuf:"varint,6,opt,name=auto_stop,json=autoStop,proto3" json:"auto_stop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceAllocation) Reset() {
	*x = ResourceAllocation{}
	mi := &file_internal_grpc_proto_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceAllocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceAllocation) ProtoMessage() {}

func (x *ResourceAllocation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceAllocation.ProtoReflect.Descriptor instead.
func (*ResourceAllocation) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_common_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceAllocation) GetSnapshot() string {
	if x != nil {
		return x.Snapshot
	}
	return ""
}

func (x *ResourceAllocation) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ResourceAllocation) GetCpu() int32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *ResourceAllocation) GetMemory() int32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *ResourceAllocation) GetDisk() int32 {
	if x != nil {
		return x.Disk
	}
	return 0
}

func (x *ResourceAllocation) GetAutoStop() int32 {
	if x != nil {
		return x.AutoStop
	}
	return 0
}

// Error response
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_internal_grpc_proto_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_common_proto_rawDescGZIP(), []int{5}
}

func (x *ErrorResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_internal_grpc_proto_common_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_common_proto_rawDesc = "" +
	"\n" +
	" internal/grpc/proto/common.proto\x12\bdispense\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8b\x01\n" +
	"\vGitHubIssue\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x05R\x06number\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x04 \x01(\tR\x04repo\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x06 \x01(\tR\x04body\"\x88\x01\n" +
	"\bGitHubPR\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x05R\x06number\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x04 \x01(\tR\x04repo\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x06 \x01(\tR\x04body\"\x97\x01\n" +
	"\bTaskData\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x128\n" +
	"\fgithub_issue\x18\x02 \x01(\v2\x15.dispense.GitHubIssueR\vgithubIssue\x12/\n" +
	"\tgithub_pr\x18\x03 \x01(\v2\x12.dispense.GitHubPRR\bgithubPr\"\x8d\x03\n" +
	"\vSandboxInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12)\n" +
	"\x04type\x18\x03 \x01(\x0e2\x15.dispense.SandboxTypeR\x04type\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12#\n" +
	"\rshell_command\x18\x05 \x01(\tR\fshellCommand\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x14\n" +
	"\x05group\x18\a \x01(\tR\x05group\x12%\n" +
	"\x0eproject_source\x18\b \x01(\tR\rprojectSource\x12?\n" +
	"\bmetadata\x18\t \x03(\v2#.dispense.SandboxInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa3\x01\n" +
	"\x12ResourceAllocation\x12\x1a\n" +
	"\bsnapshot\x18\x01 \x01(\tR\bsnapshot\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x10\n" +
	"\x03cpu\x18\x03 \x01(\x05R\x03cpu\x12\x16\n" +
	"\x06memory\x18\x04 \x01(\x05R\x06memory\x12\x12\n" +
	"\x04disk\x18\x05 \x01(\x05R\x04disk\x12\x1b\n" +
	"\tauto_stop\x18\x06 \x01(\x05R\bautoStop\"\xb9\x01\n" +
	"\rErrorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12>\n" +
	"\adetails\x18\x03 \x03(\v2$.dispense.ErrorResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\\\n" +
	"\vSandboxType\x12\x1c\n" +
	"\x18SANDBOX_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SANDBOX_TYPE_LOCAL\x10\x01\x12\x17\n" +
	"\x13SANDBOX_TYPE_REMOTE\x10\x02B\x19Z\x17cli/internal/grpc/protob\x06proto3"

var (
	file_internal_grpc_proto_common_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_common_proto_rawDescData []byte
)

func file_internal_grpc_proto_common_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_common_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_common_proto_rawDesc), len(file_internal_grpc_proto_common_proto_rawDesc)))
	})
	return file_internal_grpc_proto_common_proto_rawDescData
}

var file_internal_grpc_proto_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_grpc_proto_common_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_grpc_proto_common_proto_goTypes = []any{
	(SandboxType)(0),            // 0: dispense.SandboxType
	(*GitHubIssue)(nil),         // 1: dispense.GitHubIssue
	(*GitHubPR)(nil),            // 2: dispense.GitHubPR
	(*TaskData)(nil),            // 3: dispense.TaskData
	(*SandboxInfo)(nil),         // 4: dispense.SandboxInfo
	(*ResourceAllocation)(nil),  // 5: dispense.ResourceAllocation
	(*ErrorResponse)(nil),       // 6: dispense.ErrorResponse
	nil,                         // 7: dispense.SandboxInfo.MetadataEntry
	nil,                         // 8: dispense.ErrorResponse.DetailsEntry
	(*timestamp.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_internal_grpc_proto_common_proto_depIdxs = []int32{
	1, // 0: dispense.TaskData.github_issue:type_name -> dispense.GitHubIssue
	2, // 1: dispense.TaskData.github_pr:type_name -> dispense.GitHubPR
	0, // 2: dispense.SandboxInfo.type:type_name -> dispense.SandboxType
	9, // 3: dispense.SandboxInfo.created_at:type_name -> google.protobuf.Timestamp
	7, // 4: dispense.SandboxInfo.metadata:type_name -> dispense.SandboxInfo.MetadataEntry
	8, // 5: dispense.ErrorResponse.details:type_name -> dispense.ErrorResponse.DetailsEntry
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_common_proto_init() }
func file_internal_grpc_proto_common_proto_init() {
	if File_internal_grpc_proto_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_common_proto_rawDesc), len(file_internal_grpc_proto_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_grpc_proto_common_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_common_proto_depIdxs,
		EnumInfos:         file_internal_grpc_proto_common_proto_enumTypes,
		MessageInfos:      file_internal_grpc_proto_common_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_common_proto = out.File
	file_internal_grpc_proto_common_proto_goTypes = nil
	file_internal_grpc_proto_common_proto_depIdxs = nil
}
