// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.12.4
// source: proto/daemon.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteClaudeResponse_ResponseType int32

const (
	ExecuteClaudeResponse_STDOUT ExecuteClaudeResponse_ResponseType = 0
	ExecuteClaudeResponse_STDERR ExecuteClaudeResponse_ResponseType = 1
	ExecuteClaudeResponse_STATUS ExecuteClaudeResponse_ResponseType = 2
	ExecuteClaudeResponse_ERROR  ExecuteClaudeResponse_ResponseType = 3
)

// Enum value maps for ExecuteClaudeResponse_ResponseType.
var (
	ExecuteClaudeResponse_ResponseType_name = map[int32]string{
		0: "STDOUT",
		1: "STDERR",
		2: "STATUS",
		3: "ERROR",
	}
	ExecuteClaudeResponse_ResponseType_value = map[string]int32{
		"STDOUT": 0,
		"STDERR": 1,
		"STATUS": 2,
		"ERROR":  3,
	}
)

func (x ExecuteClaudeResponse_ResponseType) Enum() *ExecuteClaudeResponse_ResponseType {
	p := new(ExecuteClaudeResponse_ResponseType)
	*p = x
	return p
}

func (x ExecuteClaudeResponse_ResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecuteClaudeResponse_ResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_daemon_proto_enumTypes[0].Descriptor()
}

func (ExecuteClaudeResponse_ResponseType) Type() protoreflect.EnumType {
	return &file_proto_daemon_proto_enumTypes[0]
}

func (x ExecuteClaudeResponse_ResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecuteClaudeResponse_ResponseType.Descriptor instead.
func (ExecuteClaudeResponse_ResponseType) EnumDescriptor() ([]byte, []int) {
	return file_proto_daemon_proto_rawDescGZIP(), []int{7, 0}
}

type TaskStatusResponse_TaskState int32

const (
	TaskStatusResponse_PENDING   TaskStatusResponse_TaskState = 0
	TaskStatusResponse_RUNNING   TaskStatusResponse_TaskState = 1
	TaskStatusResponse_COMPLETED TaskStatusResponse_TaskState = 2
	TaskStatusResponse_FAILED    TaskStatusResponse_TaskState = 3
)

// Enum value maps for TaskStatusResponse_TaskState.
var (
	TaskStatusResponse_TaskState_name = map[int32]string{
		0: "PENDING",
		1: "RUNNING",
		2: "COMPLETED",
		3: "FAILED",
	}
	TaskStatusResponse_TaskState_value = map[string]int32{
		"PENDING":   0,
		"RUNNING":   1,
		"COMPLETED": 2,
		"FAILED":    3,
	}
)

func (x TaskStatusResponse_TaskState) Enum() *TaskStatusResponse_TaskState {
	p := new(TaskStatusResponse_TaskState)
	*p = x
	return p
}

func (x TaskStatusResponse_TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatusResponse_TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_daemon_proto_enumTypes[1].Descriptor()
}

func (TaskStatusResponse_TaskState) Type() protoreflect.EnumType {
	return &file_proto_daemon_proto_enumTypes[1]
}

func (x TaskStatusResponse_TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatusResponse_TaskState.Descriptor instead.
func (TaskStatusResponse_TaskState) EnumDescriptor() ([]byte, []int) {
	return file_proto_daemon_proto_rawDescGZIP(), []int{9, 0}
}

// Common request/response types
type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectType   string                 `protobuf:"bytes,1,opt,name=project_type,json=projectType,proto3" json:"project_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_proto_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_proto_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *InitRequest) GetProjectType() string {
	if x != nil {
		return x.ProjectType
	}
	return ""
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_proto_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_proto_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *InitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_proto_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_daemon_proto_rawDescGZIP(), []int{2}
}

type LogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogEntry      string                 `protobuf:"bytes,1,opt,name=log_entry,json=logEntry,proto3" json:"log_entry,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsResponse) Reset() {
	*x = LogsResponse{}
	mi := &file_proto_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsResponse) ProtoMessage() {}

func (x *LogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsResponse.ProtoReflect.Descriptor instead.
func (*LogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *LogsResponse) GetLogEntry() string {
	if x != nil {
		return x.LogEntry
	}
	return ""
}

func (x *LogsResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// CreateTaskRequest for creating new tasks
type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_proto_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTaskRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_proto_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CreateTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ExecuteClaudeRequest for running Claude with a prompt
type ExecuteClaudeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Prompt           string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	WorkingDirectory string                 `protobuf:"bytes,2,opt,name=working_directory,json=workingDirectory,proto3" json:"working_directory,omitempty"`
	EnvironmentVars  map[string]string      `protobuf:"bytes,3,rep,name=environment_vars,json=environmentVars,proto3" json:"environment_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExecuteClaudeRequest) Reset() {
	*x = ExecuteClaudeRequest{}
	mi := &file_proto_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteClaudeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteClaudeRequest) ProtoMessage() {}

func (x *ExecuteClaudeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteClaudeRequest.ProtoReflect.Descriptor instead.
func (*ExecuteClaudeRequest) Descriptor() ([]byte, []int) {
	return file_proto_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteClaudeRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ExecuteClaudeRequest) GetWorkingDirectory() string {
	if x != nil {
		return x.WorkingDirectory
	}
	return ""
}

func (x *ExecuteClaudeRequest) GetEnvironmentVars() map[string]string {
	if x != nil {
		return x.EnvironmentVars
	}
	return nil
}

// ExecuteClaudeResponse streams Claude execution output
type ExecuteClaudeResponse struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Type          ExecuteClaudeResponse_ResponseType `protobuf:"varint,1,opt,name=type,proto3,enum=daemon.ExecuteClaudeResponse_ResponseType" json:"type,omitempty"`
	Content       string                             `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     int64                              `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExitCode      int32                              `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`       // Only set for STATUS type
	IsFinished    bool                               `protobuf:"varint,5,opt,name=is_finished,json=isFinished,proto3" json:"is_finished,omitempty"` // Indicates if execution is complete
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteClaudeResponse) Reset() {
	*x = ExecuteClaudeResponse{}
	mi := &file_proto_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteClaudeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteClaudeResponse) ProtoMessage() {}

func (x *ExecuteClaudeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteClaudeResponse.ProtoReflect.Descriptor instead.
func (*ExecuteClaudeResponse) Descriptor() ([]byte, []int) {
	return file_proto_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteClaudeResponse) GetType() ExecuteClaudeResponse_ResponseType {
	if x != nil {
		return x.Type
	}
	return ExecuteClaudeResponse_STDOUT
}

func (x *ExecuteClaudeResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ExecuteClaudeResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ExecuteClaudeResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecuteClaudeResponse) GetIsFinished() bool {
	if x != nil {
		return x.IsFinished
	}
	return false
}

// TaskStatusRequest for checking task status
type TaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusRequest) Reset() {
	*x = TaskStatusRequest{}
	mi := &file_proto_daemon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusRequest) ProtoMessage() {}

func (x *TaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusRequest.ProtoReflect.Descriptor instead.
func (*TaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_daemon_proto_rawDescGZIP(), []int{8}
}

func (x *TaskStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// TaskStatusResponse returns current task status
type TaskStatusResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	State         TaskStatusResponse_TaskState `protobuf:"varint,1,opt,name=state,proto3,enum=daemon.TaskStatusResponse_TaskState" json:"state,omitempty"`
	Message       string                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ExitCode      int32                        `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	StartedAt     int64                        `protobuf:"varint,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    int64                        `protobuf:"varint,5,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	Error         string                       `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusResponse) Reset() {
	*x = TaskStatusResponse{}
	mi := &file_proto_daemon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusResponse) ProtoMessage() {}

func (x *TaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusResponse.ProtoReflect.Descriptor instead.
func (*TaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_daemon_proto_rawDescGZIP(), []int{9}
}

func (x *TaskStatusResponse) GetState() TaskStatusResponse_TaskState {
	if x != nil {
		return x.State
	}
	return TaskStatusResponse_PENDING
}

func (x *TaskStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskStatusResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *TaskStatusResponse) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *TaskStatusResponse) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

func (x *TaskStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ListTasksRequest for listing all tasks
type ListTasksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: filter by state
	StateFilter   TaskStatusResponse_TaskState `protobuf:"varint,1,opt,name=state_filter,json=stateFilter,proto3,enum=daemon.TaskStatusResponse_TaskState" json:"state_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_proto_daemon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_proto_daemon_proto_rawDescGZIP(), []int{10}
}

func (x *ListTasksRequest) GetStateFilter() TaskStatusResponse_TaskState {
	if x != nil {
		return x.StateFilter
	}
	return TaskStatusResponse_PENDING
}

// TaskInfo contains information about a task
type TaskInfo struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	TaskId           string                       `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Prompt           string                       `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	State            TaskStatusResponse_TaskState `protobuf:"varint,3,opt,name=state,proto3,enum=daemon.TaskStatusResponse_TaskState" json:"state,omitempty"`
	StartedAt        int64                        `protobuf:"varint,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt       int64                        `protobuf:"varint,5,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	ExitCode         int32                        `protobuf:"varint,6,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error            string                       `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	WorkingDirectory string                       `protobuf:"bytes,8,opt,name=working_directory,json=workingDirectory,proto3" json:"working_directory,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TaskInfo) Reset() {
	*x = TaskInfo{}
	mi := &file_proto_daemon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfo) ProtoMessage() {}

func (x *TaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfo.ProtoReflect.Descriptor instead.
func (*TaskInfo) Descriptor() ([]byte, []int) {
	return file_proto_daemon_proto_rawDescGZIP(), []int{11}
}

func (x *TaskInfo) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskInfo) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *TaskInfo) GetState() TaskStatusResponse_TaskState {
	if x != nil {
		return x.State
	}
	return TaskStatusResponse_PENDING
}

func (x *TaskInfo) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *TaskInfo) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

func (x *TaskInfo) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *TaskInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskInfo) GetWorkingDirectory() string {
	if x != nil {
		return x.WorkingDirectory
	}
	return ""
}

// ListTasksResponse returns list of tasks
type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskInfo            `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_proto_daemon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_proto_daemon_proto_rawDescGZIP(), []int{12}
}

func (x *ListTasksResponse) GetTasks() []*TaskInfo {
	if x != nil {
		return x.Tasks
	}
	return nil
}

var File_proto_daemon_proto protoreflect.FileDescriptor

const file_proto_daemon_proto_rawDesc = "" +
	"\n" +
	"\x12proto/daemon.proto\x12\x06daemon\"0\n" +
	"\vInitRequest\x12!\n" +
	"\fproject_type\x18\x01 \x01(\tR\vprojectType\"B\n" +
	"\fInitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\r\n" +
	"\vLogsRequest\"I\n" +
	"\fLogsResponse\x12\x1b\n" +
	"\tlog_entry\x18\x01 \x01(\tR\blogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"+\n" +
	"\x11CreateTaskRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\"a\n" +
	"\x12CreateTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xfd\x01\n" +
	"\x14ExecuteClaudeRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12+\n" +
	"\x11working_directory\x18\x02 \x01(\tR\x10workingDirectory\x12\\\n" +
	"\x10environment_vars\x18\x03 \x03(\v21.daemon.ExecuteClaudeRequest.EnvironmentVarsEntryR\x0fenvironmentVars\x1aB\n" +
	"\x14EnvironmentVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8c\x02\n" +
	"\x15ExecuteClaudeResponse\x12>\n" +
	"\x04type\x18\x01 \x01(\x0e2*.daemon.ExecuteClaudeResponse.ResponseTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x1f\n" +
	"\vis_finished\x18\x05 \x01(\bR\n" +
	"isFinished\"=\n" +
	"\fResponseType\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x00\x12\n" +
	"\n" +
	"\x06STDERR\x10\x01\x12\n" +
	"\n" +
	"\x06STATUS\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\",\n" +
	"\x11TaskStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\x9f\x02\n" +
	"\x12TaskStatusResponse\x12:\n" +
	"\x05state\x18\x01 \x01(\x0e2$.daemon.TaskStatusResponse.TaskStateR\x05state\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\x03R\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\x05 \x01(\x03R\n" +
	"finishedAt\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"@\n" +
	"\tTaskState\x12\v\n" +
	"\aPENDING\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\r\n" +
	"\tCOMPLETED\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\"[\n" +
	"\x10ListTasksRequest\x12G\n" +
	"\fstate_filter\x18\x01 \x01(\x0e2$.daemon.TaskStatusResponse.TaskStateR\vstateFilter\"\x97\x02\n" +
	"\bTaskInfo\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12:\n" +
	"\x05state\x18\x03 \x01(\x0e2$.daemon.TaskStatusResponse.TaskStateR\x05state\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\x03R\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\x05 \x01(\x03R\n" +
	"finishedAt\x12\x1b\n" +
	"\texit_code\x18\x06 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12+\n" +
	"\x11working_directory\x18\b \x01(\tR\x10workingDirectory\";\n" +
	"\x11ListTasksResponse\x12&\n" +
	"\x05tasks\x18\x01 \x03(\v2\x10.daemon.TaskInfoR\x05tasks2x\n" +
	"\x0eProjectService\x121\n" +
	"\x04Init\x12\x13.daemon.InitRequest\x1a\x14.daemon.InitResponse\x123\n" +
	"\x04Logs\x12\x13.daemon.LogsRequest\x1a\x14.daemon.LogsResponse0\x012\xe0\x02\n" +
	"\fAgentService\x121\n" +
	"\x04Init\x12\x13.daemon.InitRequest\x1a\x14.daemon.InitResponse\x12C\n" +
	"\n" +
	"CreateTask\x12\x19.daemon.CreateTaskRequest\x1a\x1a.daemon.CreateTaskResponse\x12N\n" +
	"\rExecuteClaude\x12\x1c.daemon.ExecuteClaudeRequest\x1a\x1d.daemon.ExecuteClaudeResponse0\x01\x12F\n" +
	"\rGetTaskStatus\x12\x19.daemon.TaskStatusRequest\x1a\x1a.daemon.TaskStatusResponse\x12@\n" +
	"\tListTasks\x12\x18.daemon.ListTasksRequest\x1a\x19.daemon.ListTasksResponseB\vZ\tcli/protob\x06proto3"

var (
	file_proto_daemon_proto_rawDescOnce sync.Once
	file_proto_daemon_proto_rawDescData []byte
)

func file_proto_daemon_proto_rawDescGZIP() []byte {
	file_proto_daemon_proto_rawDescOnce.Do(func() {
		file_proto_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_daemon_proto_rawDesc), len(file_proto_daemon_proto_rawDesc)))
	})
	return file_proto_daemon_proto_rawDescData
}

var file_proto_daemon_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_daemon_proto_goTypes = []any{
	(ExecuteClaudeResponse_ResponseType)(0), // 0: daemon.ExecuteClaudeResponse.ResponseType
	(TaskStatusResponse_TaskState)(0),       // 1: daemon.TaskStatusResponse.TaskState
	(*InitRequest)(nil),                     // 2: daemon.InitRequest
	(*InitResponse)(nil),                    // 3: daemon.InitResponse
	(*LogsRequest)(nil),                     // 4: daemon.LogsRequest
	(*LogsResponse)(nil),                    // 5: daemon.LogsResponse
	(*CreateTaskRequest)(nil),               // 6: daemon.CreateTaskRequest
	(*CreateTaskResponse)(nil),              // 7: daemon.CreateTaskResponse
	(*ExecuteClaudeRequest)(nil),            // 8: daemon.ExecuteClaudeRequest
	(*ExecuteClaudeResponse)(nil),           // 9: daemon.ExecuteClaudeResponse
	(*TaskStatusRequest)(nil),               // 10: daemon.TaskStatusRequest
	(*TaskStatusResponse)(nil),              // 11: daemon.TaskStatusResponse
	(*ListTasksRequest)(nil),                // 12: daemon.ListTasksRequest
	(*TaskInfo)(nil),                        // 13: daemon.TaskInfo
	(*ListTasksResponse)(nil),               // 14: daemon.ListTasksResponse
	nil,                                     // 15: daemon.ExecuteClaudeRequest.EnvironmentVarsEntry
}
var file_proto_daemon_proto_depIdxs = []int32{
	15, // 0: daemon.ExecuteClaudeRequest.environment_vars:type_name -> daemon.ExecuteClaudeRequest.EnvironmentVarsEntry
	0,  // 1: daemon.ExecuteClaudeResponse.type:type_name -> daemon.ExecuteClaudeResponse.ResponseType
	1,  // 2: daemon.TaskStatusResponse.state:type_name -> daemon.TaskStatusResponse.TaskState
	1,  // 3: daemon.ListTasksRequest.state_filter:type_name -> daemon.TaskStatusResponse.TaskState
	1,  // 4: daemon.TaskInfo.state:type_name -> daemon.TaskStatusResponse.TaskState
	13, // 5: daemon.ListTasksResponse.tasks:type_name -> daemon.TaskInfo
	2,  // 6: daemon.ProjectService.Init:input_type -> daemon.InitRequest
	4,  // 7: daemon.ProjectService.Logs:input_type -> daemon.LogsRequest
	2,  // 8: daemon.AgentService.Init:input_type -> daemon.InitRequest
	6,  // 9: daemon.AgentService.CreateTask:input_type -> daemon.CreateTaskRequest
	8,  // 10: daemon.AgentService.ExecuteClaude:input_type -> daemon.ExecuteClaudeRequest
	10, // 11: daemon.AgentService.GetTaskStatus:input_type -> daemon.TaskStatusRequest
	12, // 12: daemon.AgentService.ListTasks:input_type -> daemon.ListTasksRequest
	3,  // 13: daemon.ProjectService.Init:output_type -> daemon.InitResponse
	5,  // 14: daemon.ProjectService.Logs:output_type -> daemon.LogsResponse
	3,  // 15: daemon.AgentService.Init:output_type -> daemon.InitResponse
	7,  // 16: daemon.AgentService.CreateTask:output_type -> daemon.CreateTaskResponse
	9,  // 17: daemon.AgentService.ExecuteClaude:output_type -> daemon.ExecuteClaudeResponse
	11, // 18: daemon.AgentService.GetTaskStatus:output_type -> daemon.TaskStatusResponse
	14, // 19: daemon.AgentService.ListTasks:output_type -> daemon.ListTasksResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_daemon_proto_init() }
func file_proto_daemon_proto_init() {
	if File_proto_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_daemon_proto_rawDesc), len(file_proto_daemon_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_daemon_proto_goTypes,
		DependencyIndexes: file_proto_daemon_proto_depIdxs,
		EnumInfos:         file_proto_daemon_proto_enumTypes,
		MessageInfos:      file_proto_daemon_proto_msgTypes,
	}.Build()
	File_proto_daemon_proto = out.File
	file_proto_daemon_proto_goTypes = nil
	file_proto_daemon_proto_depIdxs = nil
}
