// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: internal/grpc/proto/dispense.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunClaudeTaskResponse_ResponseType int32

const (
	RunClaudeTaskResponse_STDOUT RunClaudeTaskResponse_ResponseType = 0
	RunClaudeTaskResponse_STDERR RunClaudeTaskResponse_ResponseType = 1
	RunClaudeTaskResponse_STATUS RunClaudeTaskResponse_ResponseType = 2
	RunClaudeTaskResponse_ERROR  RunClaudeTaskResponse_ResponseType = 3
)

// Enum value maps for RunClaudeTaskResponse_ResponseType.
var (
	RunClaudeTaskResponse_ResponseType_name = map[int32]string{
		0: "STDOUT",
		1: "STDERR",
		2: "STATUS",
		3: "ERROR",
	}
	RunClaudeTaskResponse_ResponseType_value = map[string]int32{
		"STDOUT": 0,
		"STDERR": 1,
		"STATUS": 2,
		"ERROR":  3,
	}
)

func (x RunClaudeTaskResponse_ResponseType) Enum() *RunClaudeTaskResponse_ResponseType {
	p := new(RunClaudeTaskResponse_ResponseType)
	*p = x
	return p
}

func (x RunClaudeTaskResponse_ResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunClaudeTaskResponse_ResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_grpc_proto_dispense_proto_enumTypes[0].Descriptor()
}

func (RunClaudeTaskResponse_ResponseType) Type() protoreflect.EnumType {
	return &file_internal_grpc_proto_dispense_proto_enumTypes[0]
}

func (x RunClaudeTaskResponse_ResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunClaudeTaskResponse_ResponseType.Descriptor instead.
func (RunClaudeTaskResponse_ResponseType) EnumDescriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{15, 0}
}

type StreamTaskLogsResponse_LogType int32

const (
	StreamTaskLogsResponse_STDOUT StreamTaskLogsResponse_LogType = 0
	StreamTaskLogsResponse_STDERR StreamTaskLogsResponse_LogType = 1
	StreamTaskLogsResponse_STATUS StreamTaskLogsResponse_LogType = 2
	StreamTaskLogsResponse_ERROR  StreamTaskLogsResponse_LogType = 3
)

// Enum value maps for StreamTaskLogsResponse_LogType.
var (
	StreamTaskLogsResponse_LogType_name = map[int32]string{
		0: "STDOUT",
		1: "STDERR",
		2: "STATUS",
		3: "ERROR",
	}
	StreamTaskLogsResponse_LogType_value = map[string]int32{
		"STDOUT": 0,
		"STDERR": 1,
		"STATUS": 2,
		"ERROR":  3,
	}
)

func (x StreamTaskLogsResponse_LogType) Enum() *StreamTaskLogsResponse_LogType {
	p := new(StreamTaskLogsResponse_LogType)
	*p = x
	return p
}

func (x StreamTaskLogsResponse_LogType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamTaskLogsResponse_LogType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_grpc_proto_dispense_proto_enumTypes[1].Descriptor()
}

func (StreamTaskLogsResponse_LogType) Type() protoreflect.EnumType {
	return &file_internal_grpc_proto_dispense_proto_enumTypes[1]
}

func (x StreamTaskLogsResponse_LogType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamTaskLogsResponse_LogType.Descriptor instead.
func (StreamTaskLogsResponse_LogType) EnumDescriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{24, 0}
}

// Sandbox service messages
type CreateSandboxRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BranchName      string                 `protobuf:"bytes,2,opt,name=branch_name,json=branchName,proto3" json:"branch_name,omitempty"`
	IsRemote        bool                   `protobuf:"varint,3,opt,name=is_remote,json=isRemote,proto3" json:"is_remote,omitempty"`
	Force           bool                   `protobuf:"varint,4,opt,name=force,proto3" json:"force,omitempty"`
	SkipCopy        bool                   `protobuf:"varint,5,opt,name=skip_copy,json=skipCopy,proto3" json:"skip_copy,omitempty"`
	SkipDaemon      bool                   `protobuf:"varint,6,opt,name=skip_daemon,json=skipDaemon,proto3" json:"skip_daemon,omitempty"`
	Group           string                 `protobuf:"bytes,7,opt,name=group,proto3" json:"group,omitempty"`
	Model           string                 `protobuf:"bytes,8,opt,name=model,proto3" json:"model,omitempty"`
	Task            string                 `protobuf:"bytes,9,opt,name=task,proto3" json:"task,omitempty"`
	Resources       *ResourceAllocation    `protobuf:"bytes,10,opt,name=resources,proto3" json:"resources,omitempty"`
	SourceDirectory string                 `protobuf:"bytes,11,opt,name=source_directory,json=sourceDirectory,proto3" json:"source_directory,omitempty"`
	TaskData        *TaskData              `protobuf:"bytes,12,opt,name=task_data,json=taskData,proto3" json:"task_data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateSandboxRequest) Reset() {
	*x = CreateSandboxRequest{}
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxRequest) ProtoMessage() {}

func (x *CreateSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxRequest.ProtoReflect.Descriptor instead.
func (*CreateSandboxRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSandboxRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSandboxRequest) GetBranchName() string {
	if x != nil {
		return x.BranchName
	}
	return ""
}

func (x *CreateSandboxRequest) GetIsRemote() bool {
	if x != nil {
		return x.IsRemote
	}
	return false
}

func (x *CreateSandboxRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *CreateSandboxRequest) GetSkipCopy() bool {
	if x != nil {
		return x.SkipCopy
	}
	return false
}

func (x *CreateSandboxRequest) GetSkipDaemon() bool {
	if x != nil {
		return x.SkipDaemon
	}
	return false
}

func (x *CreateSandboxRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *CreateSandboxRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateSandboxRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *CreateSandboxRequest) GetResources() *ResourceAllocation {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *CreateSandboxRequest) GetSourceDirectory() string {
	if x != nil {
		return x.SourceDirectory
	}
	return ""
}

func (x *CreateSandboxRequest) GetTaskData() *TaskData {
	if x != nil {
		return x.TaskData
	}
	return nil
}

type CreateSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandbox       *SandboxInfo           `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	Error         *ErrorResponse         `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSandboxResponse) Reset() {
	*x = CreateSandboxResponse{}
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxResponse) ProtoMessage() {}

func (x *CreateSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxResponse.ProtoReflect.Descriptor instead.
func (*CreateSandboxResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSandboxResponse) GetSandbox() *SandboxInfo {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

func (x *CreateSandboxResponse) GetError() *ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

type ListSandboxesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShowLocal     bool                   `protobuf:"varint,1,opt,name=show_local,json=showLocal,proto3" json:"show_local,omitempty"`
	ShowRemote    bool                   `protobuf:"varint,2,opt,name=show_remote,json=showRemote,proto3" json:"show_remote,omitempty"`
	Verbose       bool                   `protobuf:"varint,3,opt,name=verbose,proto3" json:"verbose,omitempty"`
	Group         string                 `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxesRequest) Reset() {
	*x = ListSandboxesRequest{}
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesRequest) ProtoMessage() {}

func (x *ListSandboxesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxesRequest.ProtoReflect.Descriptor instead.
func (*ListSandboxesRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{2}
}

func (x *ListSandboxesRequest) GetShowLocal() bool {
	if x != nil {
		return x.ShowLocal
	}
	return false
}

func (x *ListSandboxesRequest) GetShowRemote() bool {
	if x != nil {
		return x.ShowRemote
	}
	return false
}

func (x *ListSandboxesRequest) GetVerbose() bool {
	if x != nil {
		return x.Verbose
	}
	return false
}

func (x *ListSandboxesRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type ListSandboxesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandboxes     []*SandboxInfo         `protobuf:"bytes,1,rep,name=sandboxes,proto3" json:"sandboxes,omitempty"`
	Error         *ErrorResponse         `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxesResponse) Reset() {
	*x = ListSandboxesResponse{}
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesResponse) ProtoMessage() {}

func (x *ListSandboxesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxesResponse.ProtoReflect.Descriptor instead.
func (*ListSandboxesResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{3}
}

func (x *ListSandboxesResponse) GetSandboxes() []*SandboxInfo {
	if x != nil {
		return x.Sandboxes
	}
	return nil
}

func (x *ListSandboxesResponse) GetError() *ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeleteSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	DeleteAll     bool                   `protobuf:"varint,2,opt,name=delete_all,json=deleteAll,proto3" json:"delete_all,omitempty"`
	Force         bool                   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSandboxRequest) Reset() {
	*x = DeleteSandboxRequest{}
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSandboxRequest) ProtoMessage() {}

func (x *DeleteSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSandboxRequest.ProtoReflect.Descriptor instead.
func (*DeleteSandboxRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteSandboxRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *DeleteSandboxRequest) GetDeleteAll() bool {
	if x != nil {
		return x.DeleteAll
	}
	return false
}

func (x *DeleteSandboxRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type DeleteSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         *ErrorResponse         `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSandboxResponse) Reset() {
	*x = DeleteSandboxResponse{}
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSandboxResponse) ProtoMessage() {}

func (x *DeleteSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSandboxResponse.ProtoReflect.Descriptor instead.
func (*DeleteSandboxResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteSandboxResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteSandboxResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteSandboxResponse) GetError() *ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxRequest) Reset() {
	*x = GetSandboxRequest{}
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxRequest) ProtoMessage() {}

func (x *GetSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxRequest.ProtoReflect.Descriptor instead.
func (*GetSandboxRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{6}
}

func (x *GetSandboxRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

type GetSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandbox       *SandboxInfo           `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	Error         *ErrorResponse         `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxResponse) Reset() {
	*x = GetSandboxResponse{}
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxResponse) ProtoMessage() {}

func (x *GetSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxResponse.ProtoReflect.Descriptor instead.
func (*GetSandboxResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{7}
}

func (x *GetSandboxResponse) GetSandbox() *SandboxInfo {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

func (x *GetSandboxResponse) GetError() *ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

type WaitForSandboxRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Identifier     string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Group          string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WaitForSandboxRequest) Reset() {
	*x = WaitForSandboxRequest{}
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForSandboxRequest) ProtoMessage() {}

func (x *WaitForSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForSandboxRequest.ProtoReflect.Descriptor instead.
func (*WaitForSandboxRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{8}
}

func (x *WaitForSandboxRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *WaitForSandboxRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *WaitForSandboxRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type WaitForSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         *ErrorResponse         `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitForSandboxResponse) Reset() {
	*x = WaitForSandboxResponse{}
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForSandboxResponse) ProtoMessage() {}

func (x *WaitForSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForSandboxResponse.ProtoReflect.Descriptor instead.
func (*WaitForSandboxResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{9}
}

func (x *WaitForSandboxResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WaitForSandboxResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WaitForSandboxResponse) GetError() *ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetProjectSourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShowLocal     bool                   `protobuf:"varint,1,opt,name=show_local,json=showLocal,proto3" json:"show_local,omitempty"`
	ShowRemote    bool                   `protobuf:"varint,2,opt,name=show_remote,json=showRemote,proto3" json:"show_remote,omitempty"`
	Group         string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectSourcesRequest) Reset() {
	*x = GetProjectSourcesRequest{}
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectSourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectSourcesRequest) ProtoMessage() {}

func (x *GetProjectSourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectSourcesRequest.ProtoReflect.Descriptor instead.
func (*GetProjectSourcesRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{10}
}

func (x *GetProjectSourcesRequest) GetShowLocal() bool {
	if x != nil {
		return x.ShowLocal
	}
	return false
}

func (x *GetProjectSourcesRequest) GetShowRemote() bool {
	if x != nil {
		return x.ShowRemote
	}
	return false
}

func (x *GetProjectSourcesRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type GetProjectSourcesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProjectSources []string               `protobuf:"bytes,1,rep,name=project_sources,json=projectSources,proto3" json:"project_sources,omitempty"`
	Error          *ErrorResponse         `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetProjectSourcesResponse) Reset() {
	*x = GetProjectSourcesResponse{}
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectSourcesResponse) ProtoMessage() {}

func (x *GetProjectSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectSourcesResponse.ProtoReflect.Descriptor instead.
func (*GetProjectSourcesResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{11}
}

func (x *GetProjectSourcesResponse) GetProjectSources() []string {
	if x != nil {
		return x.ProjectSources
	}
	return nil
}

func (x *GetProjectSourcesResponse) GetError() *ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

// Claude service messages
type CreateClaudeTaskRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SandboxIdentifier string                 `protobuf:"bytes,1,opt,name=sandbox_identifier,json=sandboxIdentifier,proto3" json:"sandbox_identifier,omitempty"`
	TaskDescription   string                 `protobuf:"bytes,2,opt,name=task_description,json=taskDescription,proto3" json:"task_description,omitempty"`
	Model             string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	WorkingDirectory  string                 `protobuf:"bytes,4,opt,name=working_directory,json=workingDirectory,proto3" json:"working_directory,omitempty"`
	EnvironmentVars   map[string]string      `protobuf:"bytes,5,rep,name=environment_vars,json=environmentVars,proto3" json:"environment_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AnthropicApiKey   string                 `protobuf:"bytes,6,opt,name=anthropic_api_key,json=anthropicApiKey,proto3" json:"anthropic_api_key,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateClaudeTaskRequest) Reset() {
	*x = CreateClaudeTaskRequest{}
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClaudeTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClaudeTaskRequest) ProtoMessage() {}

func (x *CreateClaudeTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClaudeTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateClaudeTaskRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{12}
}

func (x *CreateClaudeTaskRequest) GetSandboxIdentifier() string {
	if x != nil {
		return x.SandboxIdentifier
	}
	return ""
}

func (x *CreateClaudeTaskRequest) GetTaskDescription() string {
	if x != nil {
		return x.TaskDescription
	}
	return ""
}

func (x *CreateClaudeTaskRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateClaudeTaskRequest) GetWorkingDirectory() string {
	if x != nil {
		return x.WorkingDirectory
	}
	return ""
}

func (x *CreateClaudeTaskRequest) GetEnvironmentVars() map[string]string {
	if x != nil {
		return x.EnvironmentVars
	}
	return nil
}

func (x *CreateClaudeTaskRequest) GetAnthropicApiKey() string {
	if x != nil {
		return x.AnthropicApiKey
	}
	return ""
}

type CreateClaudeTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Error         *ErrorResponse         `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClaudeTaskResponse) Reset() {
	*x = CreateClaudeTaskResponse{}
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClaudeTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClaudeTaskResponse) ProtoMessage() {}

func (x *CreateClaudeTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClaudeTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateClaudeTaskResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{13}
}

func (x *CreateClaudeTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateClaudeTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CreateClaudeTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateClaudeTaskResponse) GetError() *ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

type RunClaudeTaskRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SandboxIdentifier string                 `protobuf:"bytes,1,opt,name=sandbox_identifier,json=sandboxIdentifier,proto3" json:"sandbox_identifier,omitempty"`
	TaskDescription   string                 `protobuf:"bytes,2,opt,name=task_description,json=taskDescription,proto3" json:"task_description,omitempty"`
	Model             string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RunClaudeTaskRequest) Reset() {
	*x = RunClaudeTaskRequest{}
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunClaudeTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunClaudeTaskRequest) ProtoMessage() {}

func (x *RunClaudeTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunClaudeTaskRequest.ProtoReflect.Descriptor instead.
func (*RunClaudeTaskRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{14}
}

func (x *RunClaudeTaskRequest) GetSandboxIdentifier() string {
	if x != nil {
		return x.SandboxIdentifier
	}
	return ""
}

func (x *RunClaudeTaskRequest) GetTaskDescription() string {
	if x != nil {
		return x.TaskDescription
	}
	return ""
}

func (x *RunClaudeTaskRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type RunClaudeTaskResponse struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Type          RunClaudeTaskResponse_ResponseType `protobuf:"varint,1,opt,name=type,proto3,enum=dispense.RunClaudeTaskResponse_ResponseType" json:"type,omitempty"`
	Content       string                             `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     int64                              `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExitCode      int32                              `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	IsFinished    bool                               `protobuf:"varint,5,opt,name=is_finished,json=isFinished,proto3" json:"is_finished,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunClaudeTaskResponse) Reset() {
	*x = RunClaudeTaskResponse{}
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunClaudeTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunClaudeTaskResponse) ProtoMessage() {}

func (x *RunClaudeTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunClaudeTaskResponse.ProtoReflect.Descriptor instead.
func (*RunClaudeTaskResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{15}
}

func (x *RunClaudeTaskResponse) GetType() RunClaudeTaskResponse_ResponseType {
	if x != nil {
		return x.Type
	}
	return RunClaudeTaskResponse_STDOUT
}

func (x *RunClaudeTaskResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RunClaudeTaskResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RunClaudeTaskResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *RunClaudeTaskResponse) GetIsFinished() bool {
	if x != nil {
		return x.IsFinished
	}
	return false
}

type GetClaudeStatusRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SandboxIdentifier string                 `protobuf:"bytes,1,opt,name=sandbox_identifier,json=sandboxIdentifier,proto3" json:"sandbox_identifier,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetClaudeStatusRequest) Reset() {
	*x = GetClaudeStatusRequest{}
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClaudeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClaudeStatusRequest) ProtoMessage() {}

func (x *GetClaudeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClaudeStatusRequest.ProtoReflect.Descriptor instead.
func (*GetClaudeStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{16}
}

func (x *GetClaudeStatusRequest) GetSandboxIdentifier() string {
	if x != nil {
		return x.SandboxIdentifier
	}
	return ""
}

type GetClaudeStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connected     bool                   `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"`
	DaemonInfo    string                 `protobuf:"bytes,2,opt,name=daemon_info,json=daemonInfo,proto3" json:"daemon_info,omitempty"`
	WorkDir       string                 `protobuf:"bytes,3,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`
	Error         *ErrorResponse         `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClaudeStatusResponse) Reset() {
	*x = GetClaudeStatusResponse{}
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClaudeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClaudeStatusResponse) ProtoMessage() {}

func (x *GetClaudeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClaudeStatusResponse.ProtoReflect.Descriptor instead.
func (*GetClaudeStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{17}
}

func (x *GetClaudeStatusResponse) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *GetClaudeStatusResponse) GetDaemonInfo() string {
	if x != nil {
		return x.DaemonInfo
	}
	return ""
}

func (x *GetClaudeStatusResponse) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

func (x *GetClaudeStatusResponse) GetError() *ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetClaudeLogsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SandboxIdentifier string                 `protobuf:"bytes,1,opt,name=sandbox_identifier,json=sandboxIdentifier,proto3" json:"sandbox_identifier,omitempty"`
	TaskId            string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // optional
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetClaudeLogsRequest) Reset() {
	*x = GetClaudeLogsRequest{}
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClaudeLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClaudeLogsRequest) ProtoMessage() {}

func (x *GetClaudeLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClaudeLogsRequest.ProtoReflect.Descriptor instead.
func (*GetClaudeLogsRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{18}
}

func (x *GetClaudeLogsRequest) GetSandboxIdentifier() string {
	if x != nil {
		return x.SandboxIdentifier
	}
	return ""
}

func (x *GetClaudeLogsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetClaudeLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Logs          []string               `protobuf:"bytes,2,rep,name=logs,proto3" json:"logs,omitempty"`
	Error         *ErrorResponse         `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClaudeLogsResponse) Reset() {
	*x = GetClaudeLogsResponse{}
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClaudeLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClaudeLogsResponse) ProtoMessage() {}

func (x *GetClaudeLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClaudeLogsResponse.ProtoReflect.Descriptor instead.
func (*GetClaudeLogsResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{19}
}

func (x *GetClaudeLogsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetClaudeLogsResponse) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *GetClaudeLogsResponse) GetError() *ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

type ListClaudeTasksRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SandboxIdentifier string                 `protobuf:"bytes,1,opt,name=sandbox_identifier,json=sandboxIdentifier,proto3" json:"sandbox_identifier,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListClaudeTasksRequest) Reset() {
	*x = ListClaudeTasksRequest{}
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClaudeTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClaudeTasksRequest) ProtoMessage() {}

func (x *ListClaudeTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClaudeTasksRequest.ProtoReflect.Descriptor instead.
func (*ListClaudeTasksRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{20}
}

func (x *ListClaudeTasksRequest) GetSandboxIdentifier() string {
	if x != nil {
		return x.SandboxIdentifier
	}
	return ""
}

type TaskInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TaskId           string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Prompt           string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	State            string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"` // PENDING, RUNNING, COMPLETED, FAILED
	StartedAt        int64                  `protobuf:"varint,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt       int64                  `protobuf:"varint,5,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	ExitCode         int32                  `protobuf:"varint,6,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error            string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	WorkingDirectory string                 `protobuf:"bytes,8,opt,name=working_directory,json=workingDirectory,proto3" json:"working_directory,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TaskInfo) Reset() {
	*x = TaskInfo{}
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfo) ProtoMessage() {}

func (x *TaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfo.ProtoReflect.Descriptor instead.
func (*TaskInfo) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{21}
}

func (x *TaskInfo) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskInfo) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *TaskInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *TaskInfo) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *TaskInfo) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

func (x *TaskInfo) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *TaskInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskInfo) GetWorkingDirectory() string {
	if x != nil {
		return x.WorkingDirectory
	}
	return ""
}

type ListClaudeTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Tasks         []*TaskInfo            `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Error         *ErrorResponse         `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClaudeTasksResponse) Reset() {
	*x = ListClaudeTasksResponse{}
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClaudeTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClaudeTasksResponse) ProtoMessage() {}

func (x *ListClaudeTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClaudeTasksResponse.ProtoReflect.Descriptor instead.
func (*ListClaudeTasksResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{22}
}

func (x *ListClaudeTasksResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListClaudeTasksResponse) GetTasks() []*TaskInfo {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListClaudeTasksResponse) GetError() *ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

// StreamTaskLogs service messages
type StreamTaskLogsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TaskId            string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SandboxIdentifier string                 `protobuf:"bytes,2,opt,name=sandbox_identifier,json=sandboxIdentifier,proto3" json:"sandbox_identifier,omitempty"` // Sandbox identifier to route the request
	Follow            bool                   `protobuf:"varint,3,opt,name=follow,proto3" json:"follow,omitempty"`                                               // Follow mode - stream until task completes
	IncludeHistory    bool                   `protobuf:"varint,4,opt,name=include_history,json=includeHistory,proto3" json:"include_history,omitempty"`         // Include existing logs before streaming
	FromTimestamp     int64                  `protobuf:"varint,5,opt,name=from_timestamp,json=fromTimestamp,proto3" json:"from_timestamp,omitempty"`            // Start from specific timestamp (optional)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StreamTaskLogsRequest) Reset() {
	*x = StreamTaskLogsRequest{}
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTaskLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTaskLogsRequest) ProtoMessage() {}

func (x *StreamTaskLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTaskLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamTaskLogsRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{23}
}

func (x *StreamTaskLogsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StreamTaskLogsRequest) GetSandboxIdentifier() string {
	if x != nil {
		return x.SandboxIdentifier
	}
	return ""
}

func (x *StreamTaskLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *StreamTaskLogsRequest) GetIncludeHistory() bool {
	if x != nil {
		return x.IncludeHistory
	}
	return false
}

func (x *StreamTaskLogsRequest) GetFromTimestamp() int64 {
	if x != nil {
		return x.FromTimestamp
	}
	return 0
}

type StreamTaskLogsResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Type          StreamTaskLogsResponse_LogType `protobuf:"varint,1,opt,name=type,proto3,enum=dispense.StreamTaskLogsResponse_LogType" json:"type,omitempty"`
	Content       string                         `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     int64                          `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TaskCompleted bool                           `protobuf:"varint,4,opt,name=task_completed,json=taskCompleted,proto3" json:"task_completed,omitempty"` // Indicates if task finished
	TaskStatus    string                         `protobuf:"bytes,5,opt,name=task_status,json=taskStatus,proto3" json:"task_status,omitempty"`           // RUNNING, COMPLETED, FAILED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTaskLogsResponse) Reset() {
	*x = StreamTaskLogsResponse{}
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTaskLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTaskLogsResponse) ProtoMessage() {}

func (x *StreamTaskLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTaskLogsResponse.ProtoReflect.Descriptor instead.
func (*StreamTaskLogsResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{24}
}

func (x *StreamTaskLogsResponse) GetType() StreamTaskLogsResponse_LogType {
	if x != nil {
		return x.Type
	}
	return StreamTaskLogsResponse_STDOUT
}

func (x *StreamTaskLogsResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *StreamTaskLogsResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StreamTaskLogsResponse) GetTaskCompleted() bool {
	if x != nil {
		return x.TaskCompleted
	}
	return false
}

func (x *StreamTaskLogsResponse) GetTaskStatus() string {
	if x != nil {
		return x.TaskStatus
	}
	return ""
}

// Config service messages
type GetAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interactive   bool                   `protobuf:"varint,1,opt,name=interactive,proto3" json:"interactive,omitempty"` // whether to prompt if not found
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAPIKeyRequest) Reset() {
	*x = GetAPIKeyRequest{}
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAPIKeyRequest) ProtoMessage() {}

func (x *GetAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*GetAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{25}
}

func (x *GetAPIKeyRequest) GetInteractive() bool {
	if x != nil {
		return x.Interactive
	}
	return false
}

type GetAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Error         *ErrorResponse         `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAPIKeyResponse) Reset() {
	*x = GetAPIKeyResponse{}
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAPIKeyResponse) ProtoMessage() {}

func (x *GetAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*GetAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{26}
}

func (x *GetAPIKeyResponse) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *GetAPIKeyResponse) GetError() *ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

type SetAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAPIKeyRequest) Reset() {
	*x = SetAPIKeyRequest{}
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAPIKeyRequest) ProtoMessage() {}

func (x *SetAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*SetAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{27}
}

func (x *SetAPIKeyRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type SetAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         *ErrorResponse         `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAPIKeyResponse) Reset() {
	*x = SetAPIKeyResponse{}
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAPIKeyResponse) ProtoMessage() {}

func (x *SetAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*SetAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{28}
}

func (x *SetAPIKeyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetAPIKeyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SetAPIKeyResponse) GetError() *ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

type ValidateAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAPIKeyRequest) Reset() {
	*x = ValidateAPIKeyRequest{}
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAPIKeyRequest) ProtoMessage() {}

func (x *ValidateAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*ValidateAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{29}
}

func (x *ValidateAPIKeyRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type ValidateAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         *ErrorResponse         `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAPIKeyResponse) Reset() {
	*x = ValidateAPIKeyResponse{}
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAPIKeyResponse) ProtoMessage() {}

func (x *ValidateAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dispense_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*ValidateAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dispense_proto_rawDescGZIP(), []int{30}
}

func (x *ValidateAPIKeyResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateAPIKeyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidateAPIKeyResponse) GetError() *ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_internal_grpc_proto_dispense_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_dispense_proto_rawDesc = "" +
	"\n" +
	"\"internal/grpc/proto/dispense.proto\x12\bdispense\x1a internal/grpc/proto/common.proto\x1a\x1cgoogle/api/annotations.proto\"\x94\x03\n" +
	"\x14CreateSandboxRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vbranch_name\x18\x02 \x01(\tR\n" +
	"branchName\x12\x1b\n" +
	"\tis_remote\x18\x03 \x01(\bR\bisRemote\x12\x14\n" +
	"\x05force\x18\x04 \x01(\bR\x05force\x12\x1b\n" +
	"\tskip_copy\x18\x05 \x01(\bR\bskipCopy\x12\x1f\n" +
	"\vskip_daemon\x18\x06 \x01(\bR\n" +
	"skipDaemon\x12\x14\n" +
	"\x05group\x18\a \x01(\tR\x05group\x12\x14\n" +
	"\x05model\x18\b \x01(\tR\x05model\x12\x12\n" +
	"\x04task\x18\t \x01(\tR\x04task\x12:\n" +
	"\tresources\x18\n" +
	" \x01(\v2\x1c.dispense.ResourceAllocationR\tresources\x12)\n" +
	"\x10source_directory\x18\v \x01(\tR\x0fsourceDirectory\x12/\n" +
	"\ttask_data\x18\f \x01(\v2\x12.dispense.TaskDataR\btaskData\"w\n" +
	"\x15CreateSandboxResponse\x12/\n" +
	"\asandbox\x18\x01 \x01(\v2\x15.dispense.SandboxInfoR\asandbox\x12-\n" +
	"\x05error\x18\x02 \x01(\v2\x17.dispense.ErrorResponseR\x05error\"\x86\x01\n" +
	"\x14ListSandboxesRequest\x12\x1d\n" +
	"\n" +
	"show_local\x18\x01 \x01(\bR\tshowLocal\x12\x1f\n" +
	"\vshow_remote\x18\x02 \x01(\bR\n" +
	"showRemote\x12\x18\n" +
	"\averbose\x18\x03 \x01(\bR\averbose\x12\x14\n" +
	"\x05group\x18\x04 \x01(\tR\x05group\"{\n" +
	"\x15ListSandboxesResponse\x123\n" +
	"\tsandboxes\x18\x01 \x03(\v2\x15.dispense.SandboxInfoR\tsandboxes\x12-\n" +
	"\x05error\x18\x02 \x01(\v2\x17.dispense.ErrorResponseR\x05error\"k\n" +
	"\x14DeleteSandboxRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x1d\n" +
	"\n" +
	"delete_all\x18\x02 \x01(\bR\tdeleteAll\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\"z\n" +
	"\x15DeleteSandboxResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x05error\x18\x03 \x01(\v2\x17.dispense.ErrorResponseR\x05error\"3\n" +
	"\x11GetSandboxRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\"t\n" +
	"\x12GetSandboxResponse\x12/\n" +
	"\asandbox\x18\x01 \x01(\v2\x15.dispense.SandboxInfoR\asandbox\x12-\n" +
	"\x05error\x18\x02 \x01(\v2\x17.dispense.ErrorResponseR\x05error\"v\n" +
	"\x15WaitForSandboxRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x05R\x0etimeoutSeconds\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\"{\n" +
	"\x16WaitForSandboxResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x05error\x18\x03 \x01(\v2\x17.dispense.ErrorResponseR\x05error\"p\n" +
	"\x18GetProjectSourcesRequest\x12\x1d\n" +
	"\n" +
	"show_local\x18\x01 \x01(\bR\tshowLocal\x12\x1f\n" +
	"\vshow_remote\x18\x02 \x01(\bR\n" +
	"showRemote\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\"s\n" +
	"\x19GetProjectSourcesResponse\x12'\n" +
	"\x0fproject_sources\x18\x01 \x03(\tR\x0eprojectSources\x12-\n" +
	"\x05error\x18\x02 \x01(\v2\x17.dispense.ErrorResponseR\x05error\"\x89\x03\n" +
	"\x17CreateClaudeTaskRequest\x12-\n" +
	"\x12sandbox_identifier\x18\x01 \x01(\tR\x11sandboxIdentifier\x12)\n" +
	"\x10task_description\x18\x02 \x01(\tR\x0ftaskDescription\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12+\n" +
	"\x11working_directory\x18\x04 \x01(\tR\x10workingDirectory\x12a\n" +
	"\x10environment_vars\x18\x05 \x03(\v26.dispense.CreateClaudeTaskRequest.EnvironmentVarsEntryR\x0fenvironmentVars\x12*\n" +
	"\x11anthropic_api_key\x18\x06 \x01(\tR\x0fanthropicApiKey\x1aB\n" +
	"\x14EnvironmentVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x96\x01\n" +
	"\x18CreateClaudeTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12-\n" +
	"\x05error\x18\x04 \x01(\v2\x17.dispense.ErrorResponseR\x05error\"\x86\x01\n" +
	"\x14RunClaudeTaskRequest\x12-\n" +
	"\x12sandbox_identifier\x18\x01 \x01(\tR\x11sandboxIdentifier\x12)\n" +
	"\x10task_description\x18\x02 \x01(\tR\x0ftaskDescription\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\"\x8e\x02\n" +
	"\x15RunClaudeTaskResponse\x12@\n" +
	"\x04type\x18\x01 \x01(\x0e2,.dispense.RunClaudeTaskResponse.ResponseTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x1f\n" +
	"\vis_finished\x18\x05 \x01(\bR\n" +
	"isFinished\"=\n" +
	"\fResponseType\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x00\x12\n" +
	"\n" +
	"\x06STDERR\x10\x01\x12\n" +
	"\n" +
	"\x06STATUS\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\"G\n" +
	"\x16GetClaudeStatusRequest\x12-\n" +
	"\x12sandbox_identifier\x18\x01 \x01(\tR\x11sandboxIdentifier\"\xa2\x01\n" +
	"\x17GetClaudeStatusResponse\x12\x1c\n" +
	"\tconnected\x18\x01 \x01(\bR\tconnected\x12\x1f\n" +
	"\vdaemon_info\x18\x02 \x01(\tR\n" +
	"daemonInfo\x12\x19\n" +
	"\bwork_dir\x18\x03 \x01(\tR\aworkDir\x12-\n" +
	"\x05error\x18\x04 \x01(\v2\x17.dispense.ErrorResponseR\x05error\"^\n" +
	"\x14GetClaudeLogsRequest\x12-\n" +
	"\x12sandbox_identifier\x18\x01 \x01(\tR\x11sandboxIdentifier\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\"t\n" +
	"\x15GetClaudeLogsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04logs\x18\x02 \x03(\tR\x04logs\x12-\n" +
	"\x05error\x18\x03 \x01(\v2\x17.dispense.ErrorResponseR\x05error\"G\n" +
	"\x16ListClaudeTasksRequest\x12-\n" +
	"\x12sandbox_identifier\x18\x01 \x01(\tR\x11sandboxIdentifier\"\xf1\x01\n" +
	"\bTaskInfo\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\x03R\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\x05 \x01(\x03R\n" +
	"finishedAt\x12\x1b\n" +
	"\texit_code\x18\x06 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12+\n" +
	"\x11working_directory\x18\b \x01(\tR\x10workingDirectory\"\x8c\x01\n" +
	"\x17ListClaudeTasksResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12(\n" +
	"\x05tasks\x18\x02 \x03(\v2\x12.dispense.TaskInfoR\x05tasks\x12-\n" +
	"\x05error\x18\x03 \x01(\v2\x17.dispense.ErrorResponseR\x05error\"\xc7\x01\n" +
	"\x15StreamTaskLogsRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12-\n" +
	"\x12sandbox_identifier\x18\x02 \x01(\tR\x11sandboxIdentifier\x12\x16\n" +
	"\x06follow\x18\x03 \x01(\bR\x06follow\x12'\n" +
	"\x0finclude_history\x18\x04 \x01(\bR\x0eincludeHistory\x12%\n" +
	"\x0efrom_timestamp\x18\x05 \x01(\x03R\rfromTimestamp\"\x90\x02\n" +
	"\x16StreamTaskLogsResponse\x12<\n" +
	"\x04type\x18\x01 \x01(\x0e2(.dispense.StreamTaskLogsResponse.LogTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12%\n" +
	"\x0etask_completed\x18\x04 \x01(\bR\rtaskCompleted\x12\x1f\n" +
	"\vtask_status\x18\x05 \x01(\tR\n" +
	"taskStatus\"8\n" +
	"\aLogType\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x00\x12\n" +
	"\n" +
	"\x06STDERR\x10\x01\x12\n" +
	"\n" +
	"\x06STATUS\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\"4\n" +
	"\x10GetAPIKeyRequest\x12 \n" +
	"\vinteractive\x18\x01 \x01(\bR\vinteractive\"[\n" +
	"\x11GetAPIKeyResponse\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12-\n" +
	"\x05error\x18\x02 \x01(\v2\x17.dispense.ErrorResponseR\x05error\"+\n" +
	"\x10SetAPIKeyRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\"v\n" +
	"\x11SetAPIKeyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x05error\x18\x03 \x01(\v2\x17.dispense.ErrorResponseR\x05error\"0\n" +
	"\x15ValidateAPIKeyRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\"w\n" +
	"\x16ValidateAPIKeyResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x05error\x18\x03 \x01(\v2\x17.dispense.ErrorResponseR\x05error2\xc7\x0e\n" +
	"\x0fDispenseService\x12j\n" +
	"\rCreateSandbox\x12\x1e.dispense.CreateSandboxRequest\x1a\x1f.dispense.CreateSandboxResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/sandboxes\x12g\n" +
	"\rListSandboxes\x12\x1e.dispense.ListSandboxesRequest\x1a\x1f.dispense.ListSandboxesResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/sandboxes\x12t\n" +
	"\rDeleteSandbox\x12\x1e.dispense.DeleteSandboxRequest\x1a\x1f.dispense.DeleteSandboxResponse\"\"\x82\xd3\xe4\x93\x02\x1c*\x1a/v1/sandboxes/{identifier}\x12k\n" +
	"\n" +
	"GetSandbox\x12\x1b.dispense.GetSandboxRequest\x1a\x1c.dispense.GetSandboxResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/sandboxes/{identifier}\x12\x7f\n" +
	"\x0eWaitForSandbox\x12\x1f.dispense.WaitForSandboxRequest\x1a .dispense.WaitForSandboxResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/sandboxes/{identifier}/wait\x12\x83\x01\n" +
	"\x11GetProjectSources\x12\".dispense.GetProjectSourcesRequest\x1a#.dispense.GetProjectSourcesResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/sandboxes/project-sources\x12\x8e\x01\n" +
	"\x10CreateClaudeTask\x12!.dispense.CreateClaudeTaskRequest\x1a\".dispense.CreateClaudeTaskResponse\"3\x82\xd3\xe4\x93\x02-:\x01*\"(/v1/sandboxes/{sandbox_identifier}/tasks\x12o\n" +
	"\rRunClaudeTask\x12\x1e.dispense.RunClaudeTaskRequest\x1a\x1f.dispense.RunClaudeTaskResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/claude/tasks0\x01\x12\x86\x01\n" +
	"\x0fGetClaudeStatus\x12 .dispense.GetClaudeStatusRequest\x1a!.dispense.GetClaudeStatusResponse\".\x82\xd3\xe4\x93\x02(\x12&/v1/claude/{sandbox_identifier}/status\x12~\n" +
	"\rGetClaudeLogs\x12\x1e.dispense.GetClaudeLogsRequest\x1a\x1f.dispense.GetClaudeLogsResponse\",\x82\xd3\xe4\x93\x02&\x12$/v1/claude/{sandbox_identifier}/logs\x12\x85\x01\n" +
	"\x0fListClaudeTasks\x12 .dispense.ListClaudeTasksRequest\x1a!.dispense.ListClaudeTasksResponse\"-\x82\xd3\xe4\x93\x02'\x12%/v1/claude/{sandbox_identifier}/tasks\x12\x9d\x01\n" +
	"\x0eStreamTaskLogs\x12\x1f.dispense.StreamTaskLogsRequest\x1a .dispense.StreamTaskLogsResponse\"F\x82\xd3\xe4\x93\x02@\x12>/v1/sandboxes/{sandbox_identifier}/tasks/{task_id}/logs/stream0\x01\x12`\n" +
	"\tGetAPIKey\x12\x1a.dispense.GetAPIKeyRequest\x1a\x1b.dispense.GetAPIKeyResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/config/api-key\x12c\n" +
	"\tSetAPIKey\x12\x1a.dispense.SetAPIKeyRequest\x1a\x1b.dispense.SetAPIKeyResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/config/api-key\x12{\n" +
	"\x0eValidateAPIKey\x12\x1f.dispense.ValidateAPIKeyRequest\x1a .dispense.ValidateAPIKeyResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/config/api-key/validateB\x19Z\x17cli/internal/grpc/protob\x06proto3"

var (
	file_internal_grpc_proto_dispense_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_dispense_proto_rawDescData []byte
)

func file_internal_grpc_proto_dispense_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_dispense_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_dispense_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_dispense_proto_rawDesc), len(file_internal_grpc_proto_dispense_proto_rawDesc)))
	})
	return file_internal_grpc_proto_dispense_proto_rawDescData
}

var file_internal_grpc_proto_dispense_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_grpc_proto_dispense_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_internal_grpc_proto_dispense_proto_goTypes = []any{
	(RunClaudeTaskResponse_ResponseType)(0), // 0: dispense.RunClaudeTaskResponse.ResponseType
	(StreamTaskLogsResponse_LogType)(0),     // 1: dispense.StreamTaskLogsResponse.LogType
	(*CreateSandboxRequest)(nil),            // 2: dispense.CreateSandboxRequest
	(*CreateSandboxResponse)(nil),           // 3: dispense.CreateSandboxResponse
	(*ListSandboxesRequest)(nil),            // 4: dispense.ListSandboxesRequest
	(*ListSandboxesResponse)(nil),           // 5: dispense.ListSandboxesResponse
	(*DeleteSandboxRequest)(nil),            // 6: dispense.DeleteSandboxRequest
	(*DeleteSandboxResponse)(nil),           // 7: dispense.DeleteSandboxResponse
	(*GetSandboxRequest)(nil),               // 8: dispense.GetSandboxRequest
	(*GetSandboxResponse)(nil),              // 9: dispense.GetSandboxResponse
	(*WaitForSandboxRequest)(nil),           // 10: dispense.WaitForSandboxRequest
	(*WaitForSandboxResponse)(nil),          // 11: dispense.WaitForSandboxResponse
	(*GetProjectSourcesRequest)(nil),        // 12: dispense.GetProjectSourcesRequest
	(*GetProjectSourcesResponse)(nil),       // 13: dispense.GetProjectSourcesResponse
	(*CreateClaudeTaskRequest)(nil),         // 14: dispense.CreateClaudeTaskRequest
	(*CreateClaudeTaskResponse)(nil),        // 15: dispense.CreateClaudeTaskResponse
	(*RunClaudeTaskRequest)(nil),            // 16: dispense.RunClaudeTaskRequest
	(*RunClaudeTaskResponse)(nil),           // 17: dispense.RunClaudeTaskResponse
	(*GetClaudeStatusRequest)(nil),          // 18: dispense.GetClaudeStatusRequest
	(*GetClaudeStatusResponse)(nil),         // 19: dispense.GetClaudeStatusResponse
	(*GetClaudeLogsRequest)(nil),            // 20: dispense.GetClaudeLogsRequest
	(*GetClaudeLogsResponse)(nil),           // 21: dispense.GetClaudeLogsResponse
	(*ListClaudeTasksRequest)(nil),          // 22: dispense.ListClaudeTasksRequest
	(*TaskInfo)(nil),                        // 23: dispense.TaskInfo
	(*ListClaudeTasksResponse)(nil),         // 24: dispense.ListClaudeTasksResponse
	(*StreamTaskLogsRequest)(nil),           // 25: dispense.StreamTaskLogsRequest
	(*StreamTaskLogsResponse)(nil),          // 26: dispense.StreamTaskLogsResponse
	(*GetAPIKeyRequest)(nil),                // 27: dispense.GetAPIKeyRequest
	(*GetAPIKeyResponse)(nil),               // 28: dispense.GetAPIKeyResponse
	(*SetAPIKeyRequest)(nil),                // 29: dispense.SetAPIKeyRequest
	(*SetAPIKeyResponse)(nil),               // 30: dispense.SetAPIKeyResponse
	(*ValidateAPIKeyRequest)(nil),           // 31: dispense.ValidateAPIKeyRequest
	(*ValidateAPIKeyResponse)(nil),          // 32: dispense.ValidateAPIKeyResponse
	nil,                                     // 33: dispense.CreateClaudeTaskRequest.EnvironmentVarsEntry
	(*ResourceAllocation)(nil),              // 34: dispense.ResourceAllocation
	(*TaskData)(nil),                        // 35: dispense.TaskData
	(*SandboxInfo)(nil),                     // 36: dispense.SandboxInfo
	(*ErrorResponse)(nil),                   // 37: dispense.ErrorResponse
}
var file_internal_grpc_proto_dispense_proto_depIdxs = []int32{
	34, // 0: dispense.CreateSandboxRequest.resources:type_name -> dispense.ResourceAllocation
	35, // 1: dispense.CreateSandboxRequest.task_data:type_name -> dispense.TaskData
	36, // 2: dispense.CreateSandboxResponse.sandbox:type_name -> dispense.SandboxInfo
	37, // 3: dispense.CreateSandboxResponse.error:type_name -> dispense.ErrorResponse
	36, // 4: dispense.ListSandboxesResponse.sandboxes:type_name -> dispense.SandboxInfo
	37, // 5: dispense.ListSandboxesResponse.error:type_name -> dispense.ErrorResponse
	37, // 6: dispense.DeleteSandboxResponse.error:type_name -> dispense.ErrorResponse
	36, // 7: dispense.GetSandboxResponse.sandbox:type_name -> dispense.SandboxInfo
	37, // 8: dispense.GetSandboxResponse.error:type_name -> dispense.ErrorResponse
	37, // 9: dispense.WaitForSandboxResponse.error:type_name -> dispense.ErrorResponse
	37, // 10: dispense.GetProjectSourcesResponse.error:type_name -> dispense.ErrorResponse
	33, // 11: dispense.CreateClaudeTaskRequest.environment_vars:type_name -> dispense.CreateClaudeTaskRequest.EnvironmentVarsEntry
	37, // 12: dispense.CreateClaudeTaskResponse.error:type_name -> dispense.ErrorResponse
	0,  // 13: dispense.RunClaudeTaskResponse.type:type_name -> dispense.RunClaudeTaskResponse.ResponseType
	37, // 14: dispense.GetClaudeStatusResponse.error:type_name -> dispense.ErrorResponse
	37, // 15: dispense.GetClaudeLogsResponse.error:type_name -> dispense.ErrorResponse
	23, // 16: dispense.ListClaudeTasksResponse.tasks:type_name -> dispense.TaskInfo
	37, // 17: dispense.ListClaudeTasksResponse.error:type_name -> dispense.ErrorResponse
	1,  // 18: dispense.StreamTaskLogsResponse.type:type_name -> dispense.StreamTaskLogsResponse.LogType
	37, // 19: dispense.GetAPIKeyResponse.error:type_name -> dispense.ErrorResponse
	37, // 20: dispense.SetAPIKeyResponse.error:type_name -> dispense.ErrorResponse
	37, // 21: dispense.ValidateAPIKeyResponse.error:type_name -> dispense.ErrorResponse
	2,  // 22: dispense.DispenseService.CreateSandbox:input_type -> dispense.CreateSandboxRequest
	4,  // 23: dispense.DispenseService.ListSandboxes:input_type -> dispense.ListSandboxesRequest
	6,  // 24: dispense.DispenseService.DeleteSandbox:input_type -> dispense.DeleteSandboxRequest
	8,  // 25: dispense.DispenseService.GetSandbox:input_type -> dispense.GetSandboxRequest
	10, // 26: dispense.DispenseService.WaitForSandbox:input_type -> dispense.WaitForSandboxRequest
	12, // 27: dispense.DispenseService.GetProjectSources:input_type -> dispense.GetProjectSourcesRequest
	14, // 28: dispense.DispenseService.CreateClaudeTask:input_type -> dispense.CreateClaudeTaskRequest
	16, // 29: dispense.DispenseService.RunClaudeTask:input_type -> dispense.RunClaudeTaskRequest
	18, // 30: dispense.DispenseService.GetClaudeStatus:input_type -> dispense.GetClaudeStatusRequest
	20, // 31: dispense.DispenseService.GetClaudeLogs:input_type -> dispense.GetClaudeLogsRequest
	22, // 32: dispense.DispenseService.ListClaudeTasks:input_type -> dispense.ListClaudeTasksRequest
	25, // 33: dispense.DispenseService.StreamTaskLogs:input_type -> dispense.StreamTaskLogsRequest
	27, // 34: dispense.DispenseService.GetAPIKey:input_type -> dispense.GetAPIKeyRequest
	29, // 35: dispense.DispenseService.SetAPIKey:input_type -> dispense.SetAPIKeyRequest
	31, // 36: dispense.DispenseService.ValidateAPIKey:input_type -> dispense.ValidateAPIKeyRequest
	3,  // 37: dispense.DispenseService.CreateSandbox:output_type -> dispense.CreateSandboxResponse
	5,  // 38: dispense.DispenseService.ListSandboxes:output_type -> dispense.ListSandboxesResponse
	7,  // 39: dispense.DispenseService.DeleteSandbox:output_type -> dispense.DeleteSandboxResponse
	9,  // 40: dispense.DispenseService.GetSandbox:output_type -> dispense.GetSandboxResponse
	11, // 41: dispense.DispenseService.WaitForSandbox:output_type -> dispense.WaitForSandboxResponse
	13, // 42: dispense.DispenseService.GetProjectSources:output_type -> dispense.GetProjectSourcesResponse
	15, // 43: dispense.DispenseService.CreateClaudeTask:output_type -> dispense.CreateClaudeTaskResponse
	17, // 44: dispense.DispenseService.RunClaudeTask:output_type -> dispense.RunClaudeTaskResponse
	19, // 45: dispense.DispenseService.GetClaudeStatus:output_type -> dispense.GetClaudeStatusResponse
	21, // 46: dispense.DispenseService.GetClaudeLogs:output_type -> dispense.GetClaudeLogsResponse
	24, // 47: dispense.DispenseService.ListClaudeTasks:output_type -> dispense.ListClaudeTasksResponse
	26, // 48: dispense.DispenseService.StreamTaskLogs:output_type -> dispense.StreamTaskLogsResponse
	28, // 49: dispense.DispenseService.GetAPIKey:output_type -> dispense.GetAPIKeyResponse
	30, // 50: dispense.DispenseService.SetAPIKey:output_type -> dispense.SetAPIKeyResponse
	32, // 51: dispense.DispenseService.ValidateAPIKey:output_type -> dispense.ValidateAPIKeyResponse
	37, // [37:52] is the sub-list for method output_type
	22, // [22:37] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_dispense_proto_init() }
func file_internal_grpc_proto_dispense_proto_init() {
	if File_internal_grpc_proto_dispense_proto != nil {
		return
	}
	file_internal_grpc_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_dispense_proto_rawDesc), len(file_internal_grpc_proto_dispense_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_proto_dispense_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_dispense_proto_depIdxs,
		EnumInfos:         file_internal_grpc_proto_dispense_proto_enumTypes,
		MessageInfos:      file_internal_grpc_proto_dispense_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_dispense_proto = out.File
	file_internal_grpc_proto_dispense_proto_goTypes = nil
	file_internal_grpc_proto_dispense_proto_depIdxs = nil
}
